package template

import "path/filepath"

// TSSourceFiles is a list of templates of files that will be in the "app" folder of a Poly project
// if TypeScript is used as the language of choice for the portable layer.
var TSSourceFiles = []templateFile{TSConfigJSON, PackageJSON, TSGitIgnore, TSMainFile}

var TSConfigJSON = templateFile{
	FilePathRel: "tsconfig.json",
	Template: `{
  "compilerOptions": {
    "lib": ["ESNext"],
    "module": "esnext",
    "target": "esnext",
    "moduleResolution": "bundler",
    "moduleDetection": "force",
    "allowImportingTsExtensions": true,
    "noEmit": true,
    "composite": true,
    "strict": true,
    "downlevelIteration": true,
    "skipLibCheck": true,
    "jsx": "react-jsx",
    "allowSyntheticDefaultImports": true,
    "forceConsistentCasingInFileNames": true,
    "allowJs": true,
    "types": [
      "node"
    ]
  }
}
`,
	TemplateName: "TSConfigJSON",
}

var PackageJSON = templateFile{
	FilePathRel: "package.json",
	Template: `{
  "name": "{{ToKebab .AppName}}",
  "module": "main.js",
  "type": "module",
  "scripts": {
    "build": "run-s build:js build:bin",
    "build:bin": "pkg --targets node18 --output ../build/bundle build/out.js",
    "build:js": "esbuild src/main.ts --bundle --minify --platform=node --format=cjs --outfile=build/out.js"
  },
  "dependencies": {
    "poly": "git+https://github.com/poly-gui/ts-poly.git#main",
    "poly-widgets": "git+https://github.com/poly-gui/ts-poly-widgets.git#main"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^20.11.16",
    "esbuild": "^0.20.0",
    "npm-run-all": "^4.1.5",
    "pkg": "^5.8.1"
  }
}`,
	TemplateName: "PackageJSON",
}

var TSGitIgnore = templateFile{
	FilePathRel: ".gitignore",
	Template: `# Based on https://raw.githubusercontent.com/github/gitignore/main/Node.gitignore

# Logs

logs
_.log
npm-debug.log_
yarn-debug.log*
yarn-error.log*
lerna-debug.log*
.pnpm-debug.log*

# Diagnostic reports (https://nodejs.org/api/report.html)

report.[0-9]_.[0-9]_.[0-9]_.[0-9]_.json

# Runtime data

pids
_.pid
_.seed
\*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover

lib-cov

# Coverage directory used by tools like istanbul

coverage
\*.lcov

# nyc test coverage

.nyc_output

# Grunt intermediate storage (https://gruntjs.com/creating-plugins#storing-task-files)

.grunt

# Bower dependency directory (https://bower.io/)

bower_components

# node-waf configuration

.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)

build/Release

# Dependency directories

node_modules/
jspm_packages/

# Snowpack dependency directory (https://snowpack.dev/)

web_modules/

# TypeScript cache

\*.tsbuildinfo

# Optional npm cache directory

.npm

# Optional eslint cache

.eslintcache

# Optional stylelint cache

.stylelintcache

# Microbundle cache

.rpt2_cache/
.rts2_cache_cjs/
.rts2_cache_es/
.rts2_cache_umd/

# Optional REPL history

.node_repl_history

# Output of 'npm pack'

\*.tgz

# Yarn Integrity file

.yarn-integrity

# dotenv environment variable files

.env
.env.development.local
.env.test.local
.env.production.local
.env.local

# parcel-bundler cache (https://parceljs.org/)

.cache
.parcel-cache

# Next.js build output

.next
out

# Nuxt.js build / generate output

.nuxt
dist

# Gatsby files

.cache/

# Comment in the public line in if your project uses Gatsby and not Next.js

# https://nextjs.org/blog/next-9-1#public-directory-support

# public

# vuepress build output

.vuepress/dist

# vuepress v2.x temp and cache directory

.temp
.cache

# Docusaurus cache and generated files

.docusaurus

# Serverless directories

.serverless/

# FuseBox cache

.fusebox/

# DynamoDB Local files

.dynamodb/

# TernJS port file

.tern-port

# Stores VSCode versions used for testing VSCode extensions

.vscode-test

# yarn v2

.yarn/cache
.yarn/unplugged
.yarn/build-state.yml
.yarn/install-state.gz
.pnp.\*

# IntelliJ based IDEs
.idea

# Finder (MacOS) folder config
.DS_Store
`,
	TemplateName: "TSGitIgnore",
}

var TSMainFile = templateFile{
	FilePathRel: filepath.Join("src", "main.ts"),
	Template: `import { createApplication, runApplication, createWindow, StdioChannel } from "poly";

async function main() {
  const context = createApplication({
    messageChannel: new StdioChannel(),
  });

  const instance = runApplication(context);

  await createWindow(
    {
      title: "{{.AppName}}",
      description: "A Poly application written in TypeScript.",
      width: 600,
      height: 400,
      tag: "main",
    },
    context
  );

  await instance;
}

main();
`,
	TemplateName: "TSMainFile",
}
